### ISSUE TITLE
Admin import project page does not load

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#1887]
### Description

Admin import project page does not load. You see a page with a stacktrace (see below)

**Operating System:** Mac

**Browser:** Chrome

### Steps to Reproduce

1. Log in as admin
2. Go to import project

**Expected behavior:**
Import project page should appear

**Actual behavior:**
Import project page does not appear. You see an error:
```
Wed Apr 17 11:48:15 PDT 2019
There was an unexpected error (type=Internal Server Error, status=500).
/portal/admin/project/import.jsp (line: [113], column: [3]) Unable to find setter method for attribute: [commandName]
org.apache.jasper.JasperException: /portal/admin/project/import.jsp (line: [113], column: [3]) Unable to find setter method for attribute: [commandName]
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:292)
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:115)
	at org.apache.jasper.compiler.Generator$GenerateVisitor.evaluateAttribute(Generator.java:3008)
```

**Comment by hirokiterashima** [comment]
Fixed in e1dc215ebad174473e0a005e8efeb47c66914bc0
