### ISSUE TITLE
JSONException sometimes thrown when teacher logs in to site

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#1985]
### Description

1. Log in as a teacher (on production the error occurs for hirokiterashima)
2. The exception below will be thrown on the server. There is likely a problem with one of the projects. This problem does not happen for everyone.

[Description of the issue]

```
org.json.JSONException: JSONObject["techReqs"] is not a JSONObject.
	at org.json.JSONObject.getJSONObject(JSONObject.java:614)
	at org.wise.portal.domain.project.impl.ProjectMetadataImpl.populateFromJSON(ProjectMetadataImpl.java:375)
	at org.wise.portal.domain.project.impl.ProjectImpl.getMetadata(ProjectImpl.java:305)
	at org.wise.portal.presentation.web.controllers.ControllerUtil.getProjectJSON(ControllerUtil.java:242)
	at org.wise.portal.presentation.web.controllers.project.ProjectAPIController.getProjectsJSON(ProjectAPIController.java:116)
	at org.wise.portal.presentation.web.controllers.project.ProjectAPIController.getPersonalLibraryProjects(ProjectAPIController.java:93)
```

**Comment by hirokiterashima** [comment]
This is a data-error issue and can be fixed by fixing the data in the db.
