### ISSUE TITLE
When a user stays logged in long enough for the session to timeout, they are shown this error page

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#2017]
### Description

Looks like the client session times out and then tries to redirect the user to http://localhost:8080/logout which then throws an error on the server because the user is no longer logged in.

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Sep 06 13:34:46 EDT 2019
There was an unexpected error (type=Internal Server Error, status=500).
No message available
java.lang.NullPointerException
	at org.wise.portal.spring.impl.WISELogoutHandler.logout(WISELogoutHandler.java:48)
	at org.springframework.security.web.authentication.logout.CompositeLogoutHandler.logout(CompositeLogoutHandler.java:54)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:109)
```
![Screen Shot 2019-09-06 at 2 11 04 PM](https://user-images.githubusercontent.com/1036509/64450636-9094c080-d0b0-11e9-9828-4e08edd830ca.png)

**Comment by hirokiterashima** [comment]
completed in #2019
