### ISSUE TITLE
excel export throws exception

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE#246]
java.lang.NumberFormatException: For input string: "4.5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Long.parseLong(Long.java:412)
	at java.lang.Long.parseLong(Long.java:461)
	at vle.web.VLEGetXLS.setCellValue(VLEGetXLS.java:3968)
	at vle.web.VLEGetXLS.setLatestAnnotationScoreAndTimestamp(VLEGetXLS.java:3897)
	at vle.web.VLEGetXLS.setGetLatestStudentWorkStudentRows(VLEGetXLS.java:1265)
	at vle.web.VLEGetXLS.getLatestStudentWorkXLSExport(VLEGetXLS.java:1174)
	at vle.web.VLEGetXLS.doGet(VLEGetXLS.java:412)

Google Code Info:
Issue #: 245
Author: geoffrey...@gmail.com
Created On: 2011-07-28T18:15:16.000Z
Closed On:

**Comment by geoffreykwan** [comment]
No longer an issue.
