### ISSUE TITLE
RegisterStudent exception: expected session attribute 'studentAccountForm'

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#462]
This exception is thrown several times during the day. Looks like a threading issue?

url: wise_url/student/registerstudent.html?null

exception message: org.springframework.web.HttpSessionRequiredException: Expected session attribute 'studentAccountForm'

stacktrace:
org.springframework.web.HttpSessionRequiredException: Expected session attribute 'studentAccountForm'
        at org.springframework.web.method.annotation.ModelFactory.initModel(ModelFactory.java:103)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:726)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

**Comment by hirokiterashima** [comment]
This was happening because the student was on either the RegisterStudent or UpdateStudentAccount page for too long and the session expired and the studentAccountForm session object also expired. To handle it, I added and exception handler using @ExceptionHandler(HttpSessionRequiredException.class) 

Look at option 2 on this SO thread:
http://stackoverflow.com/questions/2094179/default-objects-in-spring-3-mvc-sessionattributes-when-session-expired
