### ISSUE TITLE
Forgot password wizard for student is throwing exceptions

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#464]
Based on stacktrace, it looks like accountAnswer is null. Perhaps the model is not being propagated correctly across the different parts of the wizard. This might be related to our work to move to Spring 4.

username: unknown
url: /forgotaccount/student/passwordreminder.html?null

exception message: java.lang.NullPointerException

stacktrace:
java.lang.NullPointerException
        at org.wise.portal.presentation.web.controllers.forgotaccount.student.PasswordReminderWizardController.processPage(PasswordReminderWizardController.java:153)
        at sun.reflect.GeneratedMethodAccessor555.invoke(Unknown Source)

**Comment by geoffreykwan** [comment]
Fixed
https://github.com/WISE-Community/WISE/commit/9f27f92050f5afea788699457a0592b013dc92c9
