### ISSUE TITLE
IOException retrieving wise_styles_override.css

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#492]
Look into why this is happening:

username: xyz
url: http://wise_url/author/authorproject.html?forward=filemanager&projectId=13222&command=retrieveFile&fileName=/assets/wise_styles_override.css

exception message: java.io.IOException: Could not find specified file /path_to_project_folder/assets/wise_styles_override.css

stacktrace:
java.io.IOException: Could not find specified file /path_to_project_folder/assets/wise_styles_override.css
        at org.wise.vle.utils.FileManager.getFileText(FileManager.java:261)
        at org.wise.vle.utils.FileManager.retrieveFile(FileManager.java:274)
        at org.wise.portal.presentation.web.controllers.author.project.AuthorProjectController.handleRequestInternal(AuthorProjectController.java:205)
        at sun.reflect.GeneratedMethodAccessor262.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by hirokiterashima** [comment]
wise4, won't fix.
