### ISSUE TITLE
Preview mode not working on local

### ISSUE THREAD

**Issue by vishnun** [WISE-Community/WISE#669]
Installed the system as per the guideline for Eclipse.

Created a test project but it fails to load. It says unable to read project.properties

I'm using Java 8, tomcat 9, mysql 5.5

Everything else seems to work fine except the preview. Any pointers?

**Comment by hirokiterashima** [comment]
Hi Vishnu, can you copy/paste the stack trace?

**Comment by vishnun** [comment]
Sure, here it is...

---------------------------------------------------------------------------------------
java.lang.Exception: Unable to parse project content, check project.json file. Unable to continue.
	at org.wise.portal.presentation.web.controllers.OutsideErrorController.handleRequestInternal(OutsideErrorController.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.authentication.switchuser.SwitchUserFilter.doFilter(SwitchUserFilter.java:198)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:112)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:206)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:106)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
DEBUG: JavaMail version 1.4.7
DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
DEBUG: Tables of loaded providers
DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPSSLTransport=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.smtp.SMTPTransport=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3SSLStore=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle], com.sun.mail.imap.IMAPStore=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3Store=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle]}
DEBUG: Providers Listed By Protocol: {imaps=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], imap=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtps=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], pop3s=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle], smtp=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]}
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
javax.mail.internet.AddressException: Illegal address in string ``''
	at org.springframework.mail.javamail.MimeMessageHelper.parseAddress(MimeMessageHelper.java:709)
	at org.springframework.mail.javamail.MimeMessageHelper.setTo(MimeMessageHelper.java:586)
	at org.wise.portal.service.mail.MailService.postMail(MailService.java:81)
	at org.wise.portal.service.mail.MailService.postMail(MailService.java:57)
	at org.wise.portal.spring.impl.WISESimpleMappingExceptionResolver$ExceptionEmailSender.run(WISESimpleMappingExceptionResolver.java:112)
	at java.lang.Thread.run(Thread.java:745)


----------------------------------------------------------------------------------------------

I tried debugging it but couldn't figure out. It's been a while since I worked with Java. Also note that the project is a simple one which has one activity and one step with one line of text.

I even tried it with one of the projects that I exported from the production website and tried importing it into my local setup as an admin but that too gave the same error.

**Comment by hirokiterashima** [comment]
This is probably occurring because WISE can't find the project.json file. Check your wise.properties file and check your wiseBaseDir, curriculum_base_dir and studentuploads_base_dir are pointing to the right places.

You should be able to see the project in the browser by going to your WISE_instance_url/curriculum/XYZ/project.json, where XYZ is the folder name.

For example, http://localhost:8080/curriculum/1/project.json.

You can also browse our dev mailing list. Several others had similar issues:
https://groups.google.com/forum/#!searchin/wise-dev/unable$20to$20parse%7Csort:relevance

**Comment by hirokiterashima** [comment]
Hi @vishnun were you able to resolve this issue?

**Comment by vishnun** [comment]
Hi,

I tried the steps you said. My paths are pointing to the right folders but
it's still not able to load the resource. I have wise4.project.json and to
test what you said, I copied it in project.json as well. Still doesn't work.
I restarted the server as well after the changes.

For wise base directory, does the source code need to be in there?
I've tried that as well but just confirming.

Regards,

Vishnu Narang,
Always curious.

**Comment by vishnun** [comment]
Hi Hiroki,

Still not working. Here's the config i'm using.

wiseBaseURL=http://localhost:8080/wise

wiseBaseDir=/Users/vishnunarang/Vishnu/tomcat/apache-tomcat-9.0.0.M9/webapps
/wise

curriculum_base_www=http://localhost:8080/curriculum

curriculum_base_dir=/Users/vishnunarang/Vishnu/tomcat/apache-tomcat
-9.0.0.M9/webapps/curriculum

studentuploads_base_www=http://localhost:8080/studentuploads

studentuploads_base_dir=/Users/vishnunarang/Vishnu/tomcat/apache-tomcat
-9.0.0.M9/webapps/studentuploads


Anything wrong in this?

Regards,

Vishnu Narang,
Always curious.

**Comment by hirokiterashima** [comment]
It looks good, as far as I can tell.

Few things to look for:
1. When you created the test project, it should have created a directory in your curriculum directory. Look inside "/Users/vishnunarang/Vishnu/tomcat/apache-tomcat
-9.0.0.M9/webapps/curriculum" and see if it created a directory (probably named "1"), with the content of the project ("wise.project.json" if you created a WISE4 project, "project.json" if you created a WISE5 project).

If you don't see the folder, it's likely an issue related to permissions. Make sure tomcat has write permissions to the curriculum directory.

If you see the folder, you should be able to access the contents via http://localhost:8080/curriculum/1/project.json. 

2. Try logging in as an admin and importing a project. The process is written up on this page: https://github.com/WISE-Community/WISE/wiki/WISE-Administrator-Resources

Again, when you import the project, it should create a folder inside your curriculum folder.

**Comment by vishnun** [comment]
I've done all that. It still says

*type* Status report

*message* */curriculum/1/wise4.project.json*

*description* *The requested resource is not available.*

I've even tried importing but same result. I've tried it for wise4 and
wise5 projects. Not sure where i'm going wrong.


also, noticed that there is a wise_embedded_tomcat.properties file and in
that i've given the following paths:

wiseBaseURL=/wise

wiseBaseDir=/Users/vishnunarang/git/WISE/src/main/webapp/

curriculum_base_www=/wise/curriculum

curriculum_base_dir=/Users/vishnunarang/git/WISE/src/main/webapp/curriculum

studentuploads_base_www=/wise/studentuploads

studentuploads_base_dir=/Users/vishnunarang/git/WISE/src/main/webapp/
studentuploads


These paths are for the git source code and not the ones for the tomcat
webapp. That's how i interpreted from the sample embedded properties file.
Is this correct?

Regards,

Vishnu Narang,
Always curious.

On Wed, Sep 14, 2016 at 10:24 AM, Hiroki Terashima <notifications@github.com

**Comment by vishnun** [comment]
I don't think embedded tomcat was needed but I tried it anyway :)

Regards,

Vishnu Narang,
Always curious.

**Comment by hirokiterashima** [comment]
Hi Vishnu,

Yah, the embedded-tomcat is used for WISE Local Development without IDE.

Actually, you might try that and see if that method works for you:
https://github.com/WISE-Community/WISE/wiki/How-to-Setup-WISE:-Local-Development-Environment-without-using-IDE

All of us here stopped using Eclipse a few years ago, so it is possible that the documentation is out of date. We're all using this non-IDE method most of the time. It's much easier to get started.

**Comment by vishnun** [comment]
Oh okay. I'll give that a try. Thanks.
Will let you know if it works.

Regards,

Vishnu Narang,
Always curious.

On Wed, Sep 14, 2016 at 11:40 AM, Hiroki Terashima <notifications@github.com

**Comment by vishnun** [comment]
Well the stand alone app works fine without eclipse and tomcat.

Thanks

Regards,

Vishnu Narang,
Always curious.

**Comment by hirokiterashima** [comment]
Glad to hear.

**Comment by vishnun** [comment]
Hi,

While we are at it, if I want to deploy it to a server for my lab. I can
get a centOS VM and all. But would you recommend using the tomcat guide for
server installation?
Or should I use the way I just did for local installation?

Thanks.

Regards,

Vishnu Narang,
Always curious.

**Comment by hirokiterashima** [comment]
Great! I recommend following the instructions on this page:
https://github.com/WISE-Community/WISE/wiki/How-to-Setup-WISE-on-a-Server

Let us know if you run into problems.
