### ISSUE TITLE
W5 CM: cannot export notebook using hsqldb

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#705]
Happens when trying to export Notebook items via W5 CM using hsqldb.

There's an error on the server:

Stacktrace:
[ERROR,SqlExceptionHelper,http-bio-8080-exec-10] unexpected token: Period Name in statement [SELECT n.id, n.nodeId, n.componentId, 'step number', 'step title', 'component part number', n.clientSaveTime, n.serverSaveTime, n.type, n.content, n.periodId, n.runId, n.workgroupId, g.name 'Period Name', ud.username 'Teacher Username', r.project_fk 'Project ID', GROUP_CONCAT(gu.user_fk SEPARATOR ', ') 'WISE IDs' FROM notebookItems n, workgroups w, groups_related_to_users gu, groups g, runs r, users u, user_details ud where n.runId = ? and n.workgroupId = w.id and w.group_fk = gu.group_fk and g.id = n.periodId and n.runId = r.id and r.owner_fk = u.id and u.user_details_fk = ud.id group by n.id order by workgroupId]
org.hibernate.exception.SQLGrammarException: could not prepare statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:182)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1929)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1898)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1876)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2617)
	at org.hibernate.loader.Loader.doList(Loader.java:2600)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429)
	at org.hibernate.loader.Loader.list(Loader.java:2424)

**Comment by hirokiterashima** [comment]
@geoffreykwan and I fixed this by modifying the queries to HSQLDB's liking.
commit: 44fb8b98ca0e31e3138cac3688f81be1ef1554f6
