### ISSUE TITLE
Component rubric does not appear

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#892]
How to reproduce:
1. in the AT, create a rubric for a component
2. open step preview.
3. click on rubric icon ("i") for the component.

The rubric does not appear. There's an error in the console (see below). It doesn't seem to matter how many rubrics are added.

```
angular.js:14202 Error: Specified step number out of bounds.
    at a.startTour (eval at globalEval (http://wise.berkeley.edu/wise5/lib/drawingTool/vendor.min.js), <anonymous>:17:17354)
    at NodeController.showRubric (http://wise.berkeley.edu/wise5/node/nodeController.js:484:27)
    at fn (eval at compile (http://wise.berkeley.edu/wise5/jspm_packages/github/angular/bower-angular@1.5.11/angular.js), <anonymous>:4:400)
    at HelpIconController.destination.(anonymous function) [as onClick] (http://wise.berkeley.edu/wise5/jspm_packages/github/angular/bower-angular@1.5.11/angular.js:10282:22)
    at HelpIconController.click (http://wise.berkeley.edu/wise5/themes/default/themeComponents/helpIcon/helpIcon.js:19:18)
    at fn (eval at compile (http://wise.berkeley.edu/wise5/jspm_packages/github/angular/bower-angular@1.5.11/angular.js), <anonymous>:4:269)
    at expensiveCheckFn (http://wise.berkeley.edu/wise5/jspm_packages/github/angular/bower-angular@1.5.11/angular.js:16216:18)
    at callback (http://wise.berkeley.edu/wise5/jspm_packages/github/angular/bower-angular@1.5.11/angular.js:26595:17)
    at Scope.$eval (http://wise.berkeley.edu/wise5/jspm_packages/github/angular/bower-angular@1.5.11/angular.js:17997:28)
    at Scope.$apply (http://wise.berkeley.edu/wise5/jspm_packages/github/angular/bower-angular@1.5.11/angular.js:18097:25)
```

**Comment by breity** [comment]
What component types are in the step where you're seeing this? I can't seem to reproduce.

**Comment by hirokiterashima** [comment]
Try it with a step with just HTML component and add the rubric to the component.

**Comment by breity** [comment]
Ah, I see it's when there isn't a step rubric but only component rubrics. Will fix.
