### ISSUE TITLE
WebSocket NPE

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#898]
It looks like this is happening when the WebSocket is trying to close the session.

```
java.lang.NullPointerException
	at java.util.Hashtable.get(Hashtable.java:363)
	at org.wise.portal.service.websocket.WISETextWebSocketHandler.removeSession(WISETextWebSocketHandler.java:513)
	at org.wise.portal.service.websocket.WISETextWebSocketHandler.onClose(WISETextWebSocketHandler.java:323)
	at org.wise.portal.service.websocket.WISETextWebSocketHandler.afterConnectionClosed(WISETextWebSocketHandler.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy128.afterConnectionClosed(Unknown Source)
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionClosed(WebSocketHandlerDecorator.java:85)
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionClosed(LoggingWebSocketHandlerDecorator.java:72)
	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.afterConnectionClosed(ExceptionWebSocketHandlerDecorator.java:78)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onClose(StandardWebSocketHandlerAdapter.java:141)
	at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:458)
	at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:441)
	at org.apache.tomcat.websocket.WsFrameBase.processDataControl(WsFrameBase.java:316)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:270)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:116)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:54)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:192)
	at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:178)
	at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:92)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:601)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hirokiterashima** [comment]
Steps to reproduce:
1. Log in as teacher
2. Open project in W5 AT.
3. Click on "Go Home" to go back to teacher homepage.
