### ISSUE TITLE
Fix E2E tests for MC and OR components

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#912]
E2E tests have broken for MC and OR components. See error output below. Don't use xpath for locators, as it is slow and brittle. instead, use by.id, by.model, or by.css.

```
1) WISE5 Multiple Choice Component should allow students to choose a choice and save
  Message:
    Failed: No element found using locator: By(xpath, //span[@ng-show="multipleChoiceController.saveMessage.text"])
  Stack:
    NoSuchElementError: No element found using locator: By(xpath, //span[@ng-show="multipleChoiceController.saveMessage.text"])
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:808:27
        at ManagedPromise.invokeCallback_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)Error
        at ElementArrayFinder.applyAction_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:461:27)
        at ElementArrayFinder._this.(anonymous function) [as getText] (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:103:30)
        at ElementFinder.(anonymous function) [as getText] (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:829:22)
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/multipleChoice.spec.es6:75:30)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    From: Task: Run it("should allow students to choose a choice and save") in control flow
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:79:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/multipleChoice.spec.es6:45:5)
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/multipleChoice.spec.es6:2:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)

2) WISE5 Multiple Choice Component should allow students to choose several choices and save
  Message:
    Failed: No element found using locator: By(xpath, //span[@ng-show="multipleChoiceController.saveMessage.text"])
  Stack:
    NoSuchElementError: No element found using locator: By(xpath, //span[@ng-show="multipleChoiceController.saveMessage.text"])
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:808:27
        at ManagedPromise.invokeCallback_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)Error
        at ElementArrayFinder.applyAction_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:461:27)
        at ElementArrayFinder._this.(anonymous function) [as getText] (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:103:30)
        at ElementFinder.(anonymous function) [as getText] (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:829:22)
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/multipleChoice.spec.es6:158:30)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    From: Task: Run it("should allow students to choose several choices and save") in control flow
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:79:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/multipleChoice.spec.es6:124:5)
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/multipleChoice.spec.es6:2:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)

3) WISE5 Multiple Choice Component should show previously-chosen multiple choice answer
  Message:
    Expected 'true' to be 'false'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/multipleChoice.spec.es6:185:60)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
  Message:
    Expected 'false' to be 'true'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/multipleChoice.spec.es6:186:62)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
  Message:
    Expected 'false' to be 'true'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/multipleChoice.spec.es6:197:65)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)

4) WISE5 Open Response Component should load the vle and go to node5
  Message:
    Failed: No element found using locator: By(xpath, //span[@ng-show="openResponseController.saveMessage.text"])
  Stack:
    NoSuchElementError: No element found using locator: By(xpath, //span[@ng-show="openResponseController.saveMessage.text"])
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:808:27
        at ManagedPromise.invokeCallback_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)Error
        at ElementArrayFinder.applyAction_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:461:27)
        at ElementArrayFinder._this.(anonymous function) [as getText] (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:103:30)
        at ElementFinder.(anonymous function) [as getText] (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:829:22)
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/openResponse.spec.es6:31:28)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    From: Task: Run it("should load the vle and go to node5") in control flow
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:79:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/openResponse.spec.es6:15:5)
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/openResponse.spec.es6:2:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)

5) WISE5 Open Response Component should allow students to type text and save
  Message:
    Failed: No element found using locator: By(xpath, //span[@ng-show="openResponseController.saveMessage.text"])
  Stack:
    NoSuchElementError: No element found using locator: By(xpath, //span[@ng-show="openResponseController.saveMessage.text"])
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:808:27
        at ManagedPromise.invokeCallback_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:109:7)Error
        at ElementArrayFinder.applyAction_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:461:27)
        at ElementArrayFinder._this.(anonymous function) [as getText] (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:103:30)
        at ElementFinder.(anonymous function) [as getText] (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/protractor/built/element.js:829:22)
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/openResponse.spec.es6:45:28)
        at /Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    From: Task: Run it("should allow students to type text and save") in control flow
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/node_modules/jasminewd2/index.js:79:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/openResponse.spec.es6:34:5)
        at Object.<anonymous> (/Users/hirokiterashima/Dropbox/dev/WISE/src/main/webapp/wise5/test-e2e/components/openResponse.spec.es6:2:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
```

**Comment by hirokiterashima** [comment]
tests passed! 😄
