### ISSUE TITLE
Admin -> find project run -> grading tool won't load

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#954]
### Description

Finding a run by id via the admin page and trying to view the grading tool for the run won't load the grading tool.

**Operating System:** Mac OS 10.12.6

**Browser:** Chrome 61

### Steps to Reproduce

1. Log in as admin user
2. Find project by id
3. Click on grading tool for the run

**Expected behavior:** The grading tool should load.

**Actual behavior:** The grading tool does not load. The URL flickers

### Additional Information

A NPE is thrown on the server-side
```
exception message: java.lang.NullPointerException

stacktrace:
java.lang.NullPointerException
        at org.wise.portal.presentation.web.controllers.InformationController.getUserInfo(InformationController.java:185)
        at org.wise.portal.presentation.web.controllers.InformationController.handleGetConfigWISE5(InformationController.java:859)
        at sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
...
```

**Comment by hirokiterashima** [comment]
The workaround for now is to log in as the teacher and then open the grading tool.

**Comment by hirokiterashima** [comment]
This was fixed as part of the InformationController refactoring. https://github.com/WISE-Community/WISE/pull/969
